- (CB) hopefully final versions for version numbering

diff --git a/build/buildxp b/build/buildxp
--- a/build/buildxp
+++ b/build/buildxp
@@ -1,52 +1,113 @@
 #/bin/bash
 echo "Starting $0 $*"
+# must be started in main source dir for desired version
+cd build
+eval $(get_build_nr.pl)
+mainversion=$OPENXP_MAINVER
+subversion=$OPENXP_SUBVER
+buildnr=$OPENXP_BUILD
+#
+#mainversion=$1
+#subversion=0
+#buildnr=1
+# example: version = 3.8.12-1
+# mainversion has to be 3.8 in this example
+# subversion has to be 12 in this example
+# buildnr has to be 1 in this example
+version="$mainversion"."$subversion"-"$buildnr"
 scriptdir=/home/boettger/openxp/script/
-versiondir=/home/boettger/openxp/"$1"/
-sourcedir="$versiondir"openxp/
-subversion="$1".0
+versiondir=/home/boettger/openxp/"$mainversion"/
+sourcedir=$versiondir'openxp/'
+#subversion="$1".0
 cd "$sourcedir"
-#echo $scriptdir
-#echo $versiondir
-#echo $sourcedir
-#echo $subversion
+#
+echo $scriptdir
+echo $versiondir
+echo $sourcedir
+echo -----
+echo $mainversion
+echo $subversion
+echo $buildnr
+echo $version
 pwd
 #sleep 5
+#exit 1
 # baue Beta 
-echo "Build version $1 in $sourcedir"
-case "$1" in
+echo "Build version $version in $sourcedir"
+case "$mainversion" in
    3.8)
-      echo "Updating CVS for $1 "
-      cvs up -r branch_3_7_8
+      echo "Updating CVS for $version "
+      cvs up -d -P -r branch_3_7_8
       ;;
    3.9)
-      echo "Updating CVS for $1 "
-      cvs up -A
+      echo "Updating CVS for $version "
+      cvs up -d -P -A
       ;;
     *)
         echo "Usage: $0 {3.8|3.9}"
         exit 1
         ;;
 esac
-find .  -name "*.ppu" -o -name "*.o"  -o -name "*.oo2" -o -name "*.ppo" -o -name "*.rst" -o -name "openxp" | xargs -t rm
+find .  -name "*.ppu" -o -name "*.o"  -o -name "*.oo2" -o -name "*.ppo" -o -name "*.rst" -o -name "openxp" -o -name "openxp*.exe" -o -name "openxp-*bsd" | xargs -t rm
 rm "$versiondir"output/* "$versiondir"kylixout/*
 rm compile*.log compile*.err 
-"$scriptdir"makexp $1 
+"$scriptdir"makexp $mainversion 
 datum=`date`
-subject="OXP/32 v"$1": Fatal compiler errors fpc/Linux "$datum"."
-subjectkylix="OXP/32 v"$1": Fatal compiler errors Kylix2 "$datum"."
-test -s fatal-kylix-"$subversion".log && echo "buildxp: Ooops, Kylix had fatal errors"; cat error-kylix-"$subversion".log fatal-kylix-"$subversion".log > kylix-error-"$subversion".log; elm -s "$subjectkylix" openxp-cvs@lists.sourceforge.net < kylix-error-"$subversion".log 
-test -f "openxp" || echo "buildxp: Ooops, no openxp binary"; elm -s "$subject" openxp-cvs@lists.sourceforge.net < error-"$subversion".log ; exit
+subject="OXP/32 v"$version": Fatal compiler errors fpc/Linux "$datum"."
+subjectkylix="OXP/32 v"$version": Fatal compiler errors Kylix3 "$datum"."
+subjectdos="OXP/32 v"$version": DOS Crosscomp.: Fatal compiler errors fpc/Linux "$datum"."
+subjectwin="OXP/32 v"$version": Win32 Crosscomp.: Fatal compiler errors fpc/Linux "$datum"."
+subjectdos="OXP/32 v"$version": DOS Crosscomp.: Fatal compiler errors fpc/Linux "$datum"."
+subjectos2="OXP/32 v"$version": OS/2 Crosscomp.: Fatal compiler errors fpc/Linux "$datum"."
+subjectfreebsd="OXP/32 v"$version": FreeBSD Crosscomp.: Fatal compiler errors fpc/Linux "$datum"."
+subjectnetbsd="OXP/32 v"$version": NetBSD Crosscomp.: Fatal compiler errors fpc/Linux "$datum"."
+#test -s compile-kylix-error-"$version".log && echo "buildxp: Ooops, Kylix had (fatal) errors"; elm -s "$subjectkylix" openxp-cvs@lists.sourceforge.net < compile-kylix-error-"$version".log 
+test -f ../kylixout/openxp || echo "buildxp: Ooops, Kylix had (fatal) errors"
+test -f ../kylixout/openxp || elm -s "$subjectkylix" openxp-cvs@lists.sourceforge.net < compile-kylix-error-"$version".log
+test -f "openxp" || echo "buildxp: Ooops, no openxp Linux binary" 
+test -f "openxp" || elm -s "$subject" openxp-cvs@lists.sourceforge.net < compile-fpc-error-"$version".log
+### Crosscompiler
+test -f "openxp-dos.exe" || echo "buildxp: Ooops, no openxp DOS binary" 
+#test -f "openxp-dos.exe" || elm -s "$subjectdos" openxp-cvs@lists.sourceforge.net < fpc-dos-"$version".log
+test -f "openxp-win.exe" || echo "buildxp: Ooops, no openxp Win32 binary" 
+#test -f "openxp-win.exe" || elm -s "$subjectwin" openxp-cvs@lists.sourceforge.net < fpc-win-"$version".log
+test -f "openxp-os2.exe" || echo "buildxp: Ooops, no openxp OS/2 binary" 
+#test -f "openxp-os2.exe" || elm -s "$subjectos2" openxp-cvs@lists.sourceforge.net < fpc-os2-"$version".log
+test -f "openxp-netbsd" || echo "buildxp: Ooops, no openxp NetBSD binary" 
+#test -f "openxp-netbsd" || elm -s "$subjectnetbsd" openxp-cvs@lists.sourceforge.net < fpc-netbsd-"$version".log
+test -f "openxp-freebsd" || echo "buildxp: Ooops, no openxp FreeBSD binary" 
+#test -f "openxp-freebsd" || elm -s "$subjectfreebsd" openxp-cvs@lists.sourceforge.net < fpc-freebsd-"$version".log
+###
+test -f "openxp" || chown -R boettger.users /home/boettger/openxp/*
+test -f "openxp" || exit
 ./rc openxp-d.rq
 ./rc openxp-e.rq
 ./ihs doc/openxp-d.ihq
 ./ihs doc/openxp-e.ihq
 cp -a "$versiondir"kylixout/openxp openxp-kylix
-cp -a openxp openxp-$subversion
-cp -a openxp-d.res openxp-d.res-$subversion
-cp -a openxp-e.res openxp-e.res-$subversion
-cp -a doc/openxp-d.hlp doc/openxp-d.hlp-$subversion
-cp -a doc/openxp-e.hlp doc/openxp-e.hlp-$subversion
-cp -a openxp-kylix openxp-kylix-$subversion
-tar cvIf "$versiondir"openxp-"$subversion"-linux-`date -I`.tar.bz2 openxp openxp-d.res openxp-e.res doc/openxp-d.hlp doc/openxp-e.hlp 
+cp -a openxp openxp-$version
+cp -a openxp-d.res openxp-d.res-$version
+cp -a openxp-e.res openxp-e.res-$version
+cp -a doc/openxp-d.hlp doc/openxp-d.hlp-$version
+cp -a doc/openxp-e.hlp doc/openxp-e.hlp-$version
+cp -a openxp-kylix openxp-kylix-$version
+tar cvIf "$versiondir"openxp-"$version"-linux-`date -I`.tar.bz2 openxp openxp-d.res openxp-e.res doc/openxp-d.hlp doc/openxp-e.hlp 
+test -f openxp-freebsd && tar cvIf "$versiondir"openxp-"$version"-freebsd-`date -I`.tar.bz2 openxp-freebsd openxp-d.res openxp-e.res doc/openxp-d.hlp doc/openxp-e.hlp
+test -f openxp-netbsd && tar cvIf "$versiondir"openxp-"$version"-netbsd-`date -I`.tar.bz2 openxp-netbsd openxp-d.res openxp-e.res doc/openxp-d.hlp doc/openxp-e.hlp
+test -f openxp-os2.exe && zip -9-r "$versiondir"openxp-"$version"-os2-`date -I`.zip openxp-os2.exe openxp-d.res openxp-e.res doc/openxp-d.hlp doc/openxp-e.hlp
+test -f openxp-dos.exe && zip -9-r "$versiondir"openxp-"$version"-dos-`date -I`.zip openxp-dos.exe openxp-d.res openxp-e.res doc/openxp-d.hlp doc/openxp-e.hlp
+test -f openxp-win.exe &&  zip -9 -r "$versiondir"openxp-"$version"-win32-`date -I`.zip openxp-win.exe openxp-d.res openxp-e.res doc/openxp-d.hlp doc/openxp-e.hlp
 #
 echo "Finished $0"
+
+
+
+
+
+
+
+
+
+
+
+
